export { default as About } from "./About"
export { default as Contact } from "./Contact"
export { default as Footer } from "./Footer"
export { default as Hero } from "./Hero"
export { default as Services } from "./Services"
export { default as Sidebar } from "./Sidebar"
export { default as Stats } from "./Stats"
